FROM python:3.11.3-slim

ENV PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONHASHSEED=random \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_NO_INTERACTION=1 \
    POETRY_NO_ANSI=1  \
    POETRY_VERSION=1.4.2

RUN pip install --no-cache-dir poetry==$POETRY_VERSION

ENTRYPOINT [ "poetry" ]
